name: "Actbot Action"
description: "A simple GitHub Action"
author: "ShyunnY"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.token }}
branding:
  color: blue
  icon: activity
inputs:
  token:
    default: ${{ github.token }}
    description: "github token"
