name: Test Success Jobs

on:
  pull_request:

jobs:
  assign-test:
    name: Run Assign Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Run go test ./internal/actors/assign
        run: go test ./internal/actors/assign
