name: Retest Action on PR Comment

on:
  issue_comment:
    types: [ created ]

permissions:
  contents: read

jobs:
  retest:
    if: ${{ !github.event.issue.pull_request }}
    name: Retest
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./
        name: Actbot Action
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}